Merged revisions 21862 via svnmerge from https://svn.codehaus.org/mule/branches/mule-3.1.x
........
  r21862 | franco.scavuzzo | 2011-05-09 18:02:13 -0300 (Mon, 09 May 2011) | 3 lines
  
  MULE-5517: Example Launcher requires JAVA_HOME to be set
  
  _This issue was related with the examples launcher, but also with the Mule launcher. The scripts were modified (Windows and Unix) to check if Java is installed correctly, if not an error message is thrown and Mule does not start.
........


git-svn-id: https://svn.codehaus.org/mule/branches/mule-3.x@21863 bf997673-6b11-0410-b953-e057580c5b09

diff --git a/distributions/standalone/src/main/resources/bin/launcher b/distributions/standalone/src/main/resources/bin/launcher
--- a/distributions/standalone/src/main/resources/bin/launcher
+++ b/distributions/standalone/src/main/resources/bin/launcher
@@ -1,5 +1,28 @@
 #! /bin/sh
 
+# Check for java in path
+
+JAVA=
+if [ -n "`which java 2>/dev/null`" ]
+then
+    JAVA=java
+else
+    if [ ! -z "$JAVA_HOME" ]
+    then
+        JAVA=$JAVA_HOME/bin/java
+    fi
+fi
+
+if [ "$JAVA" = "" ]
+then
+    echo "**********************************************************************"
+    echo "* ERROR: java could not be found. Please install the JRE or JDK.     *"
+    echo "* If it is already installed, configure the system variables PATH or *"
+    echo "* JAVA_HOME appropriately.                                           *"
+    echo "**********************************************************************"
+    exit 1
+fi
+
 groovyJar=`ls "$MULE_HOME"/lib/opt/groovy-all*`
 commonsCliJar=`ls "$MULE_HOME"/lib/boot/commons-cli-*.jar`
 
@@ -8,5 +31,5 @@ cp=${cp}:${groovyJar}
 cp=${cp}:${commonsCliJar}
 
 # The string passed to eval must handle spaces in paths correctly.
-COMMAND_LINE="java -Dmule.home=\"${MULE_HOME}\" -cp \"${cp}\" org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain --conf \"${MULE_HOME}/bin/launcher.conf\" $@"
+COMMAND_LINE="\"${JAVA}\" -Dmule.home=\"${MULE_HOME}\" -cp \"${cp}\" org.codehaus.groovy.tools.GroovyStarter --main groovy.ui.GroovyMain --conf \"${MULE_HOME}/bin/launcher.conf\" $@"
 eval $COMMAND_LINE
